In [1]:
import pandas as pd
import numpy as np

In [7]:
# load datasets
text_data = pd.read_csv("../dataset/phishing_text.csv")
url_data = pd.read_csv("../dataset/phishing_urls.csv")

text_data.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [8]:
url_data.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [5]:
print(text_data.info())
print(url_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18650 entries, 0 to 18649
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18650 non-null  int64
 1   Email Text  18634 non-null  object
 2   Email Type  18650 non-null  object
dtypes: int64(1), object(2)
memory usage: 437.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  object
 1   URL                         235795 non-null  object
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  object
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  object
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  object
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(5)
memory usage: 100.7+ MB
None

In [9]:
text_data.columns

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='object')

In [10]:
text_data = text_data.drop(columns=["Unnamed: 0"])

In [11]:
text_data = text_data.rename(columns={
    "Email Text": "text",
    "Email Type": "label"
})

text_data.head()

                                                text           label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [12]:
text_data["label"] = text_data["label"].map({
    "Phishing Email": 1,
    "Safe Email": 0
})

text_data.head()

                                                text  label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      0
1  the other side of * galicismos * * galicismo *...      0
2  re : equistar deal tickets are you still avail...      0
3  \nHello I am your hot lil horny toy.\n    I am...      1
4  software at incredibly low prices ( 86 % lower...      1

In [14]:
text_data = text_data.dropna()

text_data.isnull().sum()

text     0
label    0
dtype: int64

In [15]:
text_data = text_data.drop_duplicates()

print(text_data.shape)

(17538, 2)

In [16]:
import re

def clean_text(text):

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"[^a-zA-Z ]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text

In [17]:
text_data["clean_text"] = text_data["text"].apply(clean_text)

text_data.head()

,text,label,clean_text
0,"re : 6 . 1100 , disc : uniformitarianism , re ...",0,re disc uniformitarianism re sex lang dick hud...
1,the other side of * galicismos * * galicismo *...,0,the other side of galicismos galicismo is a sp...
2,re : equistar deal tickets are you still avail...,0,re equistar deal tickets are you still availab...
3,\nHello I am your hot lil horny toy.\n I am...,1,hello i am your hot lil horny toy i am the one...
4,software at incredibly low prices ( 86 % lower...,1,software at incredibly low prices lower draper...

In [18]:
url_data = url_data.drop(columns=[
    "FILENAME",
    "URL",
    "Domain",
    "Title",
    "TLD"
])

url_data.head()

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,31,24,0,100.0,1.000000,0.522907,0.061933,3,1,0,...,0,0,1,34,20,28,119,0,124,1
1,23,16,0,100.0,0.666667,0.032650,0.050207,2,1,0,...,0,0,1,50,9,8,39,0,217,1
2,29,22,0,100.0,0.866667,0.028555,0.064129,2,2,0,...,0,0,1,10,2,7,42,2,5,1
3,26,19,0,100.0,1.000000,0.522907,0.057606,3,1,0,...,1,1,1,3,27,15,22,1,31,1
4,33,26,0,100.0,1.000000,0.079963,0.059441,3,1,0,...,1,0,1,244,15,34,72,1,85,1

In [19]:
print(text_data["label"].value_counts())

print(url_data["label"].value_counts())

label
0    10980
1     6558
Name: count, dtype: int64
label
1    134850
0    100945
Name: count, dtype: int64